#!/usr/bin/env python3
import os
from sys import argv

'''
helper function 
not to be called directly
'''

def _reactified(path):
    direc = []
    nodes = path.split("/")

    nodes = nodes[1:]
    for node in nodes:
        if(node=='.'): continue
        elif(node=='..'):direc.pop()
        else: direc.append(node)

    path = ""
    for item in direc:
        path = path + "/"
        path = path + item

    return path
    

def abs_path(path):
    pwd = str(os.getcwd())#always return without / at end;
    home_path = os.getenv("HOME")#always return without / at end

    if(path[0]=='/'):
        return path
    if(path[0]=='~'):
        return home_path + path[1:]
    if(path[0]!='.'):
        return pwd + '/' + path


    return _reactified(pwd +'/'+ path)

help1 = "require 1 argument as path name to be made absolute"
if(__name__=="__main__"):
    if(len(argv)!=2):
        print(help1)
        exit()
    print(abs_path(argv[1]))
