#!/bin/sh

printf "Username for 'https://github.com': " && read username
#printf "Password for 'https://$username@github.com': " && read password

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1

curl -u $username https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
