#! /usr/bin/env python
import smtplib
from email.MIMEMultipart import MIMEMultipart
from email.MIMEText import MIMEText
from sys import argv,exit

subj = "commandline mail"
body = "message"
if(len(argv)>1):
    body = argv[1]

from srb_var import srb_pass

fromaddr = "virk2656@gmail.com"
toaddr = "srbcheema2@gmail.com"
msg = MIMEMultipart()
msg['From'] = fromaddr
msg['To'] = toaddr
msg['Subject'] = subj

msg.attach(MIMEText(body, 'plain'))

server = smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login(fromaddr, srb_pass)
text = msg.as_string()
server.sendmail(fromaddr, toaddr, text)
server.quit()

'''
also allow using unsecure apps
https://myaccount.google.com/lesssecureapps?pli=1
'''

'''
for ubuntu commandline
    read this
    https://askubuntu.com/questions/522431/how-to-send-an-email-using-command-line
'''
