#!/usr/bin/env python3
import os
from sys import argv,exit

items = os.listdir(os.getcwd())

for item in items:
    if(len(item)==2 and item[0]=='t'):
        os.system("./a.out < "+item+" > o"+item[1])
