#!/bin/sh

if [ "$#" -eq 0 ]
then
    proxx='';
elif [ "$#" -eq 1 ]
then
    proxx='172.16.20.2:3128';
fi
export http_proxy=$proxx;
export https_proxy=$proxx;
export ftp_proxy=$proxx;
echo "proxy set to $http_proxy";
