#! /usr/bin/env python3
from data_bank import data_bank
from abs_path import abs_path

bank1_name="bank1"
bank1 = data_bank(abs_path("~/.CheemaFy/remember/"+bank1_name))

from reader import argd,argl


