#! /usr/bin/env python3
from sys import argv,exit
import os

description="""
requires 3 command line argunemts
code                    cpp file
testcase generator      python3 file
testdesctiption         simple file

test desctiption file includes :
    first line contains 2 integers T A
        T => no of test files to be generated
        C => no of command line argv
    then next T lines contains C commandline arguments for testcasegen
"""
if(len(argv)!=4):
    print(description)
    exit()

script,code,testc,testd = argv

if(not os.path.exists(testd)):
    print(testd," file not found")
    exit

testd = open(testd)
l = sum(1 for line in testd)

testd.seek(0,0)
testd = testd.readlines()

T,C = testd[0].split(' ')
T=int(T)

if(os.path.isdir("cases")):
    os.system("rm -r cases")

os.system("mkdir cases")

os.system("g++ -std=c++11 "+code)
for i in range(1,T+1):
    args = testd[i].split(' ')
    if(args[-1][-1]=='\n'):
        args[-1] = args[-1][:-1]
    args = ' '.join(args)
    args = str(args)
    command = "python3 "+testc+" "+args+" > in0"+str(i)+".txt"

    print(command)
    os.system(command)
    os.system("./a.out < in0"+str(i)+".txt > out0"+str(i)+".txt")
    os.system("mv in0"+str(i)+".txt ./cases")
    os.system("mv out0"+str(i)+".txt ./cases")

os.chdir("cases")
os.system("zip -r cases.zip *")
